# Generated by Django 4.2 on 2023-10-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
